# Generated by Django 4.2.3 on 2023-08-21 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0002_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Contraseña',
            field=models.CharField(max_length=100),
        ),
    ]
