# Generated by Django 4.2.3 on 2023-08-24 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_usuarios', '0003_alter_usuario_contraseña'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='Contraseña',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=100),
        ),
    ]
